[window]
decorations = "none"

dynamic_padding = false

[window.padding]
x = 0
y = 0

[font.offset]
x = 0  # For letter spacing (default: 0)
y = 2  # For line spacing (default: 0)

[terminal]

[font]
size = 11.5


